MONGODB_SETTINGS = {
    'db': 'fakebook',
    'host': '127.0.0.1',
    'port': 27017
}

NOTIFICATION_TYPES = {
    'FRIENDLY': 'FRIEND_REQUEST',
    'CANCEL_REQUEST': 'CANCEL_REQUEST',
    'ACCEPT_REQUEST': 'ACCEPT_REQUEST'
}